### ISSUE TITLE
App Only Transfers Last Character Copied

### ISSUE THREAD

**Issue by borkmaster12** [BenGrn/EldenRingSaveCopier#10]
When attempting to use the app to transfer multiple characters at once in a row, only the most recent copied character ends up in the destination file.

My guess is that each time 'Copy' is pressed, it re-edits the copy of the data originally loaded into memory and saves the result to disk without updating the loaded copy of the destination file with the new info.

This can be circumvented by simply transferring one character per launch of the application and closing the app immediately afterwards.

**Comment by BenGrn** [comment]
Every time you click copy it copies the selected slot only from the source file and adds it to the destination slot only of the target file. Every time you click copy it writes only to the target slot not the entire file.

**Comment by SSJ3Bane** [comment]
No I was able to replicate what they were reporting.
I had an empty save that I wanted to fill with all "Freedom Project"s, went 1 to 9, 0. Opened Elden Ring and only Slot 0 had a character.

**Comment by grumd** [comment]
I think you need to close and reopen the program every time you want to copy a new character.

**Comment by BenGrn** [comment]
Fixed, multiple transfers now working.
