### ISSUE TITLE
Pressing COPY doesn't do anything

### ISSUE THREAD

**Issue by Johnaam** [BenGrn/EldenRingSaveCopier#14]
Hello!

First of all thanks a lot for this program. I'm trying to copy the file, I select my destination files but nothing happens when I click on "copy". How do I make run it correctly?

**Comment by BenGrn** [comment]
You *MUST* select characters and slots to copy from and to. If you don't the copy button will not be enabled.

**Comment by Johnaam** [comment]
I got it working! thanks so much it works perfectly.
