### ISSUE TITLE
Account Flag

### ISSUE THREAD

**Issue by its-fel** [BenGrn/EldenRingSaveCopier#15]
Does using this tool run the risk of getting out game save flagged by Elden Ring's native Anti cheat system if all we want to do is move a character(s) from a different save over to our own save? I know that you can't just drag and drop a downloaded save game because that will end with you getting "Inappropriate Activity Detected". 

Additionally, on to the tool now, from my testing I noticed that we are unable to transfer more than one character at a time. I will try to move a character named EXAMPLE1 to my 3rd save slot named REPLACEME and it will work. However, if I follow that up with trying to place EXAMPLE1 to my 4th save slot (to create a duplicate character which is helpful to save scum/dupe) it only adds EXAMPLE1 to save slot 4 and not save slot 3. Unless I close the program after overriding save slot 3, then reopen the program, and redo the steps except this time go to save slot 4. I had to repeat this 7 times since I wanted EXAMPLE1 in save slot 3, 4, 5, 6, 7, 8, and 9. Not sure if that makes sense but other than it being a little more time-consuming it isn't the biggest deal. 

Thank you for the tool and please get back to me about whether or not this tool runs the risk of getting our save flagged.

**Comment by BenGrn** [comment]
The only people that can answer questions regarding account flagging is From Software.
