### ISSUE TITLE
VirusTotal flagged this 6 out of 69 scanners. Malware?

### ISSUE THREAD

**Issue by Broletariate** [BenGrn/EldenRingSaveCopier#17]
VirusTotal flagged this multiple times as 
**(1)** "Malwarebytes: MachineLearning/Anomalous.97%" 
**(2)** "Bkav Pro: W32.AIDetectNet.01" (3) "Ikarus: Trojan-Ransom.FileCrypter" 
**(4)** "MaxSecure: Trojan.Malware.300983.susgen" 
**(5)** "Webroot: W32.Hack.Tool" 
**(6)** "SecureAge APEX: Malicious"

Is this a false-positive or is something _fishy_ going on? I'd LOVE to continue using this awesome app, but not at the risk of whatever all that is.

**Comment by DrHopeful** [comment]
Same issue here.

**Comment by rectumdestroyer** [comment]
That's common for alot of automated scripts. Essentially, what this tool does is it copies hexadecimal values from your old file to your new save file. Some VirusTotal AVs flags it as malicious because it doesn't understand the intended use for it, only it's heuristics i.e. accessing %APPDATA% to copy values that it thinks is a possible malicious payload. This tool isn't malicious so you got nothing to worry about

**Comment by Broletariate** [comment]
> That's common for alot of automated scripts. Essentially, what this tool does is it copies hexadecimal values from your old file to your new save file. Some VirusTotal AVs flags it as malicious because it doesn't understand the intended use for it, only it's heuristics i.e. accessing %APPDATA% to copy values that it thinks is a possible malicious payload. This tool isn't malicious so you got nothing to worry about

I've still asked the admins to look into it in a support ticket. We'll see if it's a false-positive for sure as I'm not taking any chances now a days. I'll close the issue if it turns out to be nothing. I'm hoping the author would comment on the matter.

**Comment by BenGrn** [comment]
This has been answered many many times. Anti virus use signatures and behavior/patterns to identify viruses. This means they don't rely on seeing an exact virus before they can identify it. It also means there is a possibility of false positives. This application opens a files and modifies another. This is exactly the same as what some viruses do. The reason for releasing this on GitHub as opposed to game mod forums is so the wider public can see the source code, and GitHub removes identified malware very quickly. This is a very simple program and 5 mins of looking at the code will show it does nothing malicious.
