### ISSUE TITLE
It is supposed to work on patch 1.04 too?

### ISSUE THREAD

**Issue by Galcian79** [BenGrn/EldenRingSaveCopier#18]
I followed the instructions step by step. Twice checked if the character is copied on slot. It's there.
Unfortunately it still says it cannot load the game save.

**Comment by Galcian79** [comment]
I found a solution. It seems you STILL need to create a character on the new save file for this. Copying on an empty save doesn't work. You should make it clear on the guide.
Anyway grest work with the tool, you saved my life!

**Comment by BenGrn** [comment]
The guide on reddit explicitly states you need to create at least one character on the new save.
