### ISSUE TITLE
Multi account mod 

### ISSUE THREAD

**Issue by Lendon95** [BenGrn/EldenRingSaveCopier#19]
i was thinking about making custom starting classes by using this mod as a tool to import them. 
Does it work with save slots from different accounts? 
Am I allowed to include this exe in my page on nexus mod?

**Comment by BenGrn** [comment]
This will work for multiple source accounts. You will need to select a different source file each time you try to copy.
Best practice would be to link to the release page here to ensure users have access to the latest version with any bug fixes.
