### ISSUE TITLE
Can you add support for .co2 files

### ISSUE THREAD

**Issue by MohandL3G** [BenGrn/EldenRingSaveCopier#20]
Now that [Seamless Co-op](https://www.nexusmods.com/eldenring/mods/510) has been released it uses .co2 files instead of .sl2 file.
I have to copy it away from the save file rename it to .co2 and then use it, it'll be better if you can add support to it.

**Comment by JustAnOkapi** [comment]
+1

**Comment by BenGrn** [comment]
.co2 support added
