### ISSUE TITLE
Save File Failed to Copy

### ISSUE THREAD

**Issue by LadyCatakins** [BenGrn/EldenRingSaveCopier#21]
Hi there! So i'm having a strange issue that I haven't found a fix to. I have the most recent version of the tool, and I cant get the copy to be successful. It keeps turning red and saying "Failed". I made sure the source and destination were accurate, and that the save file I was copying was not corrupt. any idea what could be causing this? Thank you!

**Comment by SpencerJo** [comment]
I am having this issue also.

I have used the correct files for both source and destinations and selected the copy from and copy to dropdown menu

Result = Failed

**Comment by SpencerJo** [comment]
I figured it out.
It wont overwrite the existing file.

**Comment by BenGrn** [comment]
Any failures are usually permission based. Check antivirus logs and try running as admin if problem persists.
