### ISSUE TITLE
Elden ring can't load the save

### ISSUE THREAD

**Issue by AzraelsRaven** [BenGrn/EldenRingSaveCopier#22]
I copied a save file that i found on nexus mod manager, i've been trying to get it to work in that it has no issue right up until i try and boot up into the main menu. It says "Cannot load saved data" and will not progress from there. i have tried to verify the local files(steam) tried to put my old save back in and restarting the program. None of which have worked, please help!

**Comment by BenGrn** [comment]
Please ensure the save game you are copying to has at least one character created on it prior to copying.
