### ISSUE TITLE
Copy Button Doesn't Show

### ISSUE THREAD

**Issue by Its-Poppy** [BenGrn/EldenRingSaveCopier#30]
I might be missing something but all I get is "Select Source and Destination file and characters". I have both file and character selected in both source and destination but I'm not getting anything. I just want to add that I'm no coder and I don't use Github much so I'm not sure if there are steps that I've missed

**Comment by xPhrenzy** [comment]
Having the same issue

**Comment by Its-Poppy** [comment]
> Having the same issue

I found one on the nexus (nexus mods) that works like a dream. I hate to post against all the work that this guy's done, and I'm certainly not trying to stop people using this one. I have no doubt that it works, it might just be a system requirement issue or the fact that I'm unfamiliar with this stuff. But if you're struggling it might be worth a look, there's also a video tutorial with it

**Comment by SuxACux** [comment]
Found out the problem, the source and the destination can't be the same file. So just make a copy of your save files and use that as the source.
