### ISSUE TITLE
WARNING: The executable file in this post is a  very nasty trojan virus

### ISSUE THREAD

**Issue by operator436** [BenGrn/EldenRingSaveCopier#32]
This file is laced with a trojan horse. Run it on virustotal.com and see for yourself.
Here are my results. So you don't even have to download it and run it to see the truth!
https://www.virustotal.com/gui/file/aaa4d76c4514bafa56afa85dcf9c69c8e489a3be737b9e444c6c7e33d132a762

**Comment by BenGrn** [comment]
You're an absolute clown. The source is available for viewing and you can compile yourself. False positives occur from patterns within the code such as local file access and modification, which is exactly what this utility does.
