### ISSUE TITLE
This file has a virus and I attached a link to virustotal proving it. Making you a hacker clown!

### ISSUE THREAD

**Issue by operator436** [BenGrn/EldenRingSaveCopier#33]
A hacker clown the FBI is now notified about. I hope they catch your sorry ass....... BITCH!

**Comment by operator436** [comment]
Now go fuck yourself, eat shit and die like a good criminal.

**Comment by operator436** [comment]
See you soon cunt.

**Comment by operator436** [comment]
"It's just a pattern in the software mis identified".. laughable. People believe that horse shit eh?

**Comment by operator436** [comment]
You want to bot the most powerful gaming rigs with the fastest internet. Great way to do it by taking advantage of kids playing video games. And I'm the clown?

**Comment by operator436** [comment]
I see this all the time for gaming tools on the nexus. Cheap site with a bunch of trojans hosted. Only gay unexperienced worthless wanna be hackers do it like that. Pathetic.

**Comment by BenGrn** [comment]
I see you are new here. Time to leave.
