### ISSUE TITLE
can't see hidden folders using the browser from the save copier on steam deck

### ISSUE THREAD

**Issue by acarperscarper** [BenGrn/EldenRingSaveCopier#34]
HI, trying to copy a downloaded save over to seamless co-op on steam deck. I ran the exe using wine but i can't select the hidden steam folder using the browser from the save copier and can't figure out how to get it to show hidden folders. I've tried right clicking and clicking properties but no window pops up. I tried copying over the save file to a separate folder in my documents folder, editing/replacing it using the save copier, and then copying that file to my save location but i realized that won't work after going through the save files' readme. Any help would be appreciated.

**Comment by olieja** [comment]
I just downloaded this and tried today and I'm also having the same issue (also using steam deck). I found and made a copy of my save file on my steam deck to use as a source, but when I try to access the destination to copy it to on my steam deck it will not display the hidden folders. Was this ever resolved?
