### ISSUE TITLE
Nothing I do works

### ISSUE THREAD

**Issue by Monstarella** [BenGrn/EldenRingSaveCopier#36]
I've exhausted every option and piece of information available to get this software to work.
I was under the illusion that despite the note being from two years ago, stating that, both there has to be version compatiblity/synch, that it had been updated to work with cracked EldRing and current Seamless COOP mod Pre-SOTE patch Elden Ring.

The programes says, in not clear language to delete ER000.Bak file;
This process ends up ovewriting and/or deleting on of the bak files and leaves only one left.
A ER000.sl2.bak fil

I've done multiple different variations of trying to complete this process to no avail.

Either there are steps messing, the software doesn't work due to being poorly coded, outdated or there massive usererror.

**Comment by BenGrn** [comment]
There are nearly 500k downloads and people are reporting it still works perfectly with DLC.
There have even been videos made on how to use.
https://www.youtube.com/watch?v=zukGovoeYvA

I'm going to bet it's user error.
The ER0000.bak should be auto deleted, however some device security stops this sometimes. The instructions tell you to ensure it was deleted.
