### ISSUE TITLE
Copy a character from an account with ER DLC to an account without DLC?

### ISSUE THREAD

**Issue by grumd** [BenGrn/EldenRingSaveCopier#39]
Using your amazing tool I can copy the character from one account to another, but if another account doesn't have the DLC installed, the game gives me an error "The following additional components not found: Shadow of the Erdtree". Is it possible to add new functionality to fix this issue?

**Comment by Herofille** [comment]
yeah thats an issue for me to , id like if you can add an fix ti this real quick

**Comment by BenGrn** [comment]
There is no fix for this. This would include cleaning the entire save file for anything referencing the dlc and would take months to attempt to understand the entire file to even try.

On 15 Oct 2024, at 10:05 PM, Herofille ***@***.***> wrote:

﻿

yeah thats an issue for me to , id like if you can add an fix ti this real quick
