### ISSUE TITLE
The copy button doesn't work

### ISSUE THREAD

**Issue by Bar2co** [BenGrn/EldenRingSaveCopier#4]

**Comment by BenGrn** [comment]
You must have different files selected in the source and destination areas. You then must open each drop down list and select which character you want to copy from and which character to copy to. Once you have done this the copy button will light up.

**Comment by BenGrn** [comment]
No others reporting issue, tested ok. User error.

**Comment by sauronshotdogs** [comment]
I am having the same issue. Different files selected, shows different things in the dropdown menu, but can't copy. V.0.1 works fine

**Comment by BenGrn** [comment]
> 

You must open each dropdown menu and select the character.

**Comment by sauronshotdogs** [comment]
I have done so, but still can't copy in v0.2
