### ISSUE TITLE
create a readme 

### ISSUE THREAD

**Issue by nuel77** [BenGrn/EldenRingSaveCopier#5]
create a readme to show how to use

**Comment by nuel77** [comment]
First, backup all your saves.

Then, be sure to have a 'original' save file in steam (usually just create a character, and then quit the game).

Then, you need to copy the cracked save (an .sl2 file) and put in a folder (rename it to something similar, like 'cracked saved' - I've put mine in the desktop.)

Then you open the .exe file, and select this cracked save as Source File.

Then, as destination, you have to select the original save file (the one on appdata). After that, you click to start the process.

This means the .exe file will use the source file (cracked save) and replace it in the original save file (where steam version will use) - transferring all your progress to the 'original' save file.

**Comment by BenGrn** [comment]
- the source save is not edited by this tool.
- the destination file has a backup created, ER0000.backup1 prior to writing to the file.
- you do not need to relocate files.
- the UI is self documenting, and only contains 4 fields and a copy button. Further instructions should not be necessary. If you managed to install the "cracked" version of this game you should be able to use this simple tool.
