### ISSUE TITLE
Do I risk to be banned by duplicating my own savegame?

### ISSUE THREAD

**Issue by Stivenzino** [BenGrn/EldenRingSaveCopier#6]
Pretty much title. I'd like to have 2 separate savegame, one for singleplayer that I keep levelling and one for multiplayer. But don't want to do another run. I would like to know if I risk to be banned for duplicating my own savegame.

**Comment by gecusdevus** [comment]
@Stivenzino i dont think they have the ability to detect you from doing that

**Comment by Stivenzino** [comment]
Does this still worth with the new patch?

**Comment by gaspropot** [comment]
> Does this still worth with the new patch?

Yes! Just checked, works like a charm.

**Comment by BenGrn** [comment]
Patches have to support previous version save games. As for being banned only From Software can answer that.
