### ISSUE TITLE
'This app can't run on your PC' error

### ISSUE THREAD

**Issue by spreef** [BenGrn/EldenRingSaveCopier#7]
When launching the exe, I am greeted with the above mentioned error from windows. I'm running windows 10 (pro).
I really don't know how to start resolving this error. Please help.

**Comment by BenGrn** [comment]
Check the exe properties and ensure it’s not blocked.

On 18 Mar 2022, at 12:35 pm, spreef ***@***.***> wrote:

﻿

When launching the exe, I am greated with the above mentioned error from windows. I'm running windows 10 (pro).
I really don't know how to start resolving this error. Please help.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBenGrn%2FEldenRingSaveCopier%2Fissues%2F7&data=04%7C01%7C%7C0e85760eefb241de8a8a08da087f9606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831641318875743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HtoQKqO9JSlkcNGCgUtWNpiiasIAXLpx6VlksdbXFwM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANKBNR5E72L6QCHK2KR6SWDVAPMWDANCNFSM5RAQJXIQ&data=04%7C01%7C%7C0e85760eefb241de8a8a08da087f9606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831641318875743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pv3XGoTAvbtZxWUgwu2pVsEsOChZqI%2BRIOQuRHFbAUU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0e85760eefb241de8a8a08da087f9606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831641318875743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gar%2Bk0FFjVQS6n4bQnhx8Fr4VYojPTdwdxLb%2FZGtvVQ%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0e85760eefb241de8a8a08da087f9606%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831641318875743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GQYqsfZdh66Ai2SwkJ22q%2B6rQZSRKBB42mgSFzUZp00%3D&reserved=0>.

**Comment by spreef** [comment]
I double checked and all of that was in order, and it still didn't work. 
The weird part is, I just downloaded it with Chrome instead of my default browser (firefox) and now it does works!
(Might be that firefox does not appreciate .exe files I guess?)

**Comment by DjLeChuck** [comment]
In my case both Chrome and Windows are not happy with this executable, but nevermind just have to say them "Yeah yeah I know, it's potentially unsafe to launch this, but let me do it!" 😄

**Comment by BenGrn** [comment]
You can also clone the git into Visual Studio and compile yourself if required.

**Comment by kaivizzz** [comment]
Having this issue as well….tried on Chrome, Brave, and Firefox

**Comment by BenGrn** [comment]
> Having this issue as well….tried on Chrome, Brave, and Firefox

Check your anti-virus and make sure it's not blocked. Feel free to clone and compile yourself. This is an issue with your PC environment not the application. 25k + downloads at the moment and two people with this issue.

**Comment by kaivizzz** [comment]
Turned out the issue was with Webroot, antivirus software. Had it disabled and tried on 2 different PCs. Finally uninstalled the software and the app opened without issue
