### ISSUE TITLE
Is it possible to downpatch / downgrade a save file? 

### ISSUE THREAD

**Issue by I0000days** [BenGrn/EldenRingSaveCopier#8]
Hello, I'm in a pickle. 1.02.3 patch ran like a dream on my PC, last two patches introduced horrible frame drops and stutters, making the game unplayable for me. My question is, do you think it is possible to downpatch a 1.03.1 save file to run on version 1.02.3 of the game?

**Comment by BenGrn** [comment]
Currently no. As future updates may add areas, items and additional information to each save this would require extensive work each and every patch.
