### ISSUE TITLE
Might be broken?

### ISSUE THREAD

**Issue by Lighwan** [BenGrn/EldenRingSaveCopier#9]
Copying file to another account just gives me "failed loading save data" error in game.
![kuva](https://user-images.githubusercontent.com/68567124/159669267-f6b97bb2-54d0-4ff3-bc54-2d3def08cb7d.png)

**Comment by BenGrn** [comment]
You need to delete the ER0000.bak file from your steam save game folder as per the instructions within the copy tool.

**Comment by captain-steve-853** [comment]
I also got this issue after deleting the ER0000.bak file. I fixed it by creating a dummy character on my destination account, then copying the save over. I chose to overwrite the dummy character, not sure if it works copying to a blank slot (it probably would though)
